/*     */ package com.ancient.thaumicgadgets.init;
/*     */ 
/*     */ import com.ancient.thaumicgadgets.proxy.CommonProxy;
/*     */ import net.minecraft.block.Block;
/*     */ import net.minecraft.init.Blocks;
/*     */ import net.minecraft.init.Items;
/*     */ import net.minecraft.item.EnumDyeColor;
/*     */ import net.minecraft.item.Item;
/*     */ import net.minecraft.item.ItemStack;
/*     */ import net.minecraft.util.ResourceLocation;
/*     */ import net.minecraftforge.fml.common.registry.GameRegistry;
/*     */ import thaumcraft.api.ThaumcraftApi;
/*     */ import thaumcraft.api.aspects.Aspect;
/*     */ import thaumcraft.api.aspects.AspectList;
/*     */ import thaumcraft.api.blocks.BlocksTC;
/*     */ import thaumcraft.api.crafting.CrucibleRecipe;
/*     */ import thaumcraft.api.crafting.IArcaneRecipe;
/*     */ import thaumcraft.api.crafting.InfusionRecipe;
/*     */ import thaumcraft.api.crafting.ShapedArcaneRecipe;
/*     */ import thaumcraft.api.crafting.ShapelessArcaneRecipe;
/*     */ import thaumcraft.api.items.ItemsTC;
/*     */
/*     */ 
/*     */ 
/*     */ 
/*     */ public class ModRecipes
/*     */ {
/*     */   public static void InitRecipes() {

    ModMultiBlocks.InitMultiblocks();

/*  29 */     ThaumcraftApi.addCrucibleRecipe(new ResourceLocation("tg", "light_metal"), new CrucibleRecipe("TG_LIGHT_METAL@1", new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(Items.GOLD_INGOT), (new AspectList()).add(Aspect.LIGHT, 75).add(Aspect.ENERGY, 35).add(Aspect.AURA, 25)));
/*     */     
/*  31 */     ThaumcraftApi.addCrucibleRecipe(new ResourceLocation("tg", "shade_metal"), new CrucibleRecipe("TG_SHADOW_METAL@1", new ItemStack(ModItems.INGOT_SHADE), new ItemStack(Items.GOLD_INGOT), (new AspectList()).add(Aspect.DARKNESS, 75).add(Aspect.VOID, 35).add(Aspect.AURA, 25)));
/*     */ 
/*     */     
/*  34 */     ThaumcraftApi.addCrucibleRecipe(new ResourceLocation("tg", "light_ore"), new CrucibleRecipe("TG_LIGHT_METAL@1", new ItemStack(ModBlocks.ORE_LIGHT), new ItemStack(Blocks.GOLD_ORE), (new AspectList()).add(Aspect.LIGHT, 50).add(Aspect.ENERGY, 25).add(Aspect.AURA, 20)));
/*     */     
/*  36 */     ThaumcraftApi.addCrucibleRecipe(new ResourceLocation("tg", "shade_ore"), new CrucibleRecipe("TG_SHADOW_METAL@1", new ItemStack(ModBlocks.ORE_SHADE), new ItemStack(Blocks.GOLD_ORE), (new AspectList()).add(Aspect.DARKNESS, 50).add(Aspect.VOID, 25).add(Aspect.AURA, 20)));
/*     */     
/*  38 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "spinning_wheel"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "spinning_wheel"), "TG_WEAVING", 10, (new AspectList()).add(Aspect.ORDER, 5).add(Aspect.AIR, 5), new ItemStack(ModBlocks.SPINNING_WHEEL), new Object[] { "A B", " C ", Character.valueOf('A'), Items.IRON_INGOT, Character.valueOf('B'), Blocks.PLANKS, Character.valueOf('C'), BlocksTC.tableWood }));
/*     */     
/*  40 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "cutting_tools"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "cutting_tools"), "TG_JEWELLERY@1", 0, new AspectList(), new ItemStack(ModItems.TOOL_GEMCUTTER), new Object[] { "ABC", "DDD", Character.valueOf('A'), Items.QUARTZ, Character.valueOf('B'), Items.FLINT, Character.valueOf('C'), Items.IRON_INGOT, Character.valueOf('D'), Items.STICK }));
/*     */     
/*  42 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "extruder"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "extruder"), "TG_STONE_EXTRUDER", 0, (new AspectList()).add(Aspect.ENTROPY, 4).add(Aspect.EARTH, 8), new ItemStack(ModBlocks.EXTRUDER), new Object[] { " A ", "BDC", "EDE", Character.valueOf('A'), ItemsTC.thaumiumPick, Character.valueOf('B'), Items.WATER_BUCKET, Character.valueOf('C'), Items.LAVA_BUCKET, Character.valueOf('D'), BlocksTC.stoneArcane, Character.valueOf('E'), BlocksTC.plankGreatwood }));
/*  43 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "extruder_up"), new InfusionRecipe("TG_OBSIDIAN_EXTRUDER", new ItemStack(Item.getItemFromBlock(ModBlocks.EXTRUDER_UP)), 3, (new AspectList()).add(Aspect.MAGIC, 50).add(Aspect.EARTH, 150).add(Aspect.FIRE, 150).add(Aspect.EXCHANGE, 250), new ItemStack(Item.getItemFromBlock(ModBlocks.EXTRUDER)), new Object[] { new ItemStack(Item.getItemFromBlock(Blocks.OBSIDIAN)), new ItemStack(Item.getItemFromBlock(Blocks.OBSIDIAN)), new ItemStack(Item.getItemFromBlock(Blocks.OBSIDIAN)), new ItemStack(Item.getItemFromBlock(Blocks.OBSIDIAN)), new ItemStack(Items.LAVA_BUCKET), new ItemStack(Items.LAVA_BUCKET), new ItemStack(Items.WATER_BUCKET), new ItemStack(Items.WATER_BUCKET) }));

/*  47 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "primal_sword"), new InfusionRecipe("TG_PRIMAL_WEAPON", new ItemStack(ModItems.SWORD_PRIMAL), 10, (new AspectList()).add(Aspect.METAL, 500).add(Aspect.AVERSION, 500).add(Aspect.MAGIC, 250).add(Aspect.AURA, 100).add(Aspect.EXCHANGE, 100).add(Aspect.ORDER, 100).add(Aspect.ENTROPY, 100).add(Aspect.AIR, 100).add(Aspect.FIRE, 100).add(Aspect.EARTH, 100).add(Aspect.WATER, 100), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new Object[] { new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(BlocksTC.logGreatwood), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.voidSword), new ItemStack(ItemsTC.voidSword) }));
/*  48 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "primal_axe"), new InfusionRecipe("TG_PRIMAL_WEAPON", new ItemStack(ModItems.AXE_PRIMAL), 12, (new AspectList()).add(Aspect.METAL, 500).add(Aspect.AVERSION, 500).add(Aspect.MAGIC, 250).add(Aspect.AURA, 100).add(Aspect.EXCHANGE, 100).add(Aspect.ORDER, 100).add(Aspect.ENTROPY, 100).add(Aspect.AIR, 100).add(Aspect.FIRE, 100).add(Aspect.EARTH, 100).add(Aspect.WATER, 100), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new Object[] { new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(BlocksTC.logGreatwood), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.voidAxe), new ItemStack(ItemsTC.voidAxe) }));
/*  49 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "primal_hammer"), new InfusionRecipe("TG_PRIMAL_WEAPON", new ItemStack(ModItems.HAMMER_PRIMAL), 15, (new AspectList()).add(Aspect.METAL, 500).add(Aspect.AVERSION, 500).add(Aspect.MAGIC, 250).add(Aspect.AURA, 100).add(Aspect.EXCHANGE, 100).add(Aspect.ORDER, 100).add(Aspect.ENTROPY, 100).add(Aspect.AIR, 100).add(Aspect.FIRE, 100).add(Aspect.EARTH, 100).add(Aspect.WATER, 100), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new Object[] { new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.ingots, 1, 1), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(BlocksTC.logGreatwood), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.voidPick), new ItemStack(ItemsTC.voidSword) }));
/*     */
/*  65 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "light_block"), new ResourceLocation("recipes"), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new Object[] { "AAA", "AAA", "AAA", Character.valueOf('A'), ModItems.INGOT_LIGHT });
/*  66 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "shade_block"), new ResourceLocation("recipes"), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new Object[] { "AAA", "AAA", "AAA", Character.valueOf('A'), ModItems.INGOT_SHADE });
/*     */     
/*  68 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "light_ingot"), new ResourceLocation("recipes"), new ItemStack(ModItems.INGOT_LIGHT, 9), new Object[] { "A", Character.valueOf('A'), ModBlocks.LIGHT_BLOCK });
/*  69 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "shade_ingot"), new ResourceLocation("recipes"), new ItemStack(ModItems.INGOT_SHADE, 9), new Object[] { "A", Character.valueOf('A'), ModBlocks.SHADE_BLOCK });
/*     */     
/*  71 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "light_nugget"), new ResourceLocation("recipes"), new ItemStack(ModItems.NUGGET_LIGHT, 9), new Object[] { "A", Character.valueOf('A'), ModItems.INGOT_LIGHT });
/*  72 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "shade_nugget"), new ResourceLocation("recipes"), new ItemStack(ModItems.NUGGET_SHADE, 9), new Object[] { "A", Character.valueOf('A'), ModItems.INGOT_SHADE });
/*     */     
/*  74 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "light_ingot2"), new ResourceLocation("recipes"), new ItemStack(ModItems.INGOT_LIGHT), new Object[] { "AAA", "AAA", "AAA", Character.valueOf('A'), ModItems.NUGGET_LIGHT });
/*  75 */     GameRegistry.addShapedRecipe(new ResourceLocation("tg", "shade_ingot2"), new ResourceLocation("recipes"), new ItemStack(ModItems.INGOT_SHADE), new Object[] { "AAA", "AAA", "AAA", Character.valueOf('A'), ModItems.NUGGET_SHADE });
/*     */     
/*  77 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "light_pickaxe"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.PICKAXE_LIGHT), 4, (new AspectList()).add(Aspect.LIGHT, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ItemsTC.thaumiumPick), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  78 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "shade_pickaxe"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.PICKAXE_SHADE), 4, (new AspectList()).add(Aspect.DARKNESS, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ItemsTC.thaumiumPick), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  80 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "light_axe"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.AXE_LIGHT), 4, (new AspectList()).add(Aspect.LIGHT, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ItemsTC.thaumiumAxe), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  81 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "shade_axe"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.AXE_SHADE), 4, (new AspectList()).add(Aspect.DARKNESS, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ItemsTC.thaumiumAxe), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  83 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "light_shovel"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.SHOVEL_LIGHT), 4, (new AspectList()).add(Aspect.LIGHT, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10), new ItemStack(ItemsTC.thaumiumShovel), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  84 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "shade_shovel"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.SHOVEL_SHADE), 4, (new AspectList()).add(Aspect.DARKNESS, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10), new ItemStack(ItemsTC.thaumiumShovel), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  86 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "light_hoe"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.HOE_LIGHT), 4, (new AspectList()).add(Aspect.LIGHT, 20).add(Aspect.AURA, 10).add(Aspect.EXCHANGE, 20), new ItemStack(ItemsTC.thaumiumHoe), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  87 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "shade_hoe"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.HOE_SHADE), 4, (new AspectList()).add(Aspect.DARKNESS, 20).add(Aspect.AURA, 10).add(Aspect.EXCHANGE, 20), new ItemStack(ItemsTC.thaumiumHoe), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  89 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "light_shears"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.SHEARS_LIGHT), 4, (new AspectList()).add(Aspect.MAGIC, 12).add(Aspect.EARTH, 12).add(Aspect.LIGHT, 20).add(Aspect.AURA, 10).add(Aspect.EXCHANGE, 20), new ItemStack((Item)Items.SHEARS), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  90 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "shade_shears"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.SHEARS_SHADE), 4, (new AspectList()).add(Aspect.MAGIC, 12).add(Aspect.EARTH, 12).add(Aspect.DARKNESS, 20).add(Aspect.AURA, 10).add(Aspect.EXCHANGE, 20), new ItemStack((Item)Items.SHEARS), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  92 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "sword_light"), (new InfusionRecipe("TG_LIGHT_METAL", new ItemStack(ModItems.SWORD_LIGHT), 8, (new AspectList()).add(Aspect.METAL, 250).add(Aspect.AVERSION, 250).add(Aspect.MAGIC, 100).add(Aspect.AURA, 25).add(Aspect.EXCHANGE, 100), new ItemStack(ItemsTC.thaumiumSword), new Object[] { new ItemStack(Item.getItemFromBlock(BlocksTC.logGreatwood)), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ItemsTC.ingots, 1, 1) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  93 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "sword_shade"), (new InfusionRecipe("TG_SHADOW_METAL", new ItemStack(ModItems.SWORD_SHADE), 8, (new AspectList()).add(Aspect.METAL, 250).add(Aspect.AVERSION, 250).add(Aspect.MAGIC, 100).add(Aspect.AURA, 25).add(Aspect.EXCHANGE, 100), new ItemStack(ItemsTC.thaumiumSword), new Object[] { new ItemStack(Item.getItemFromBlock(BlocksTC.logGreatwood)), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ItemsTC.ingots, 1, 1) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  95 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "scythe_light"), (new InfusionRecipe("TG_LIGHT_METAL@2", new ItemStack(ModItems.SCYTHE_LIGHT), 4, (new AspectList()).add(Aspect.LIGHT, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ModItems.SCYTHE_THAUM), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_instruments")));
/*  96 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "scythe_shade"), (new InfusionRecipe("TG_SHADOW_METAL@2", new ItemStack(ModItems.SCYTHE_SHADE), 4, (new AspectList()).add(Aspect.DARKNESS, 30).add(Aspect.AURA, 15).add(Aspect.EXCHANGE, 30), new ItemStack(ModItems.SCYTHE_THAUM), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_instruments")));
/*     */     
/*  98 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "scythe_thaum"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "scythe_thaum"), "TG_SCYTHES", 75, (new AspectList()).add(Aspect.AIR, 1).add(Aspect.FIRE, 1).add(Aspect.WATER, 1).add(Aspect.EARTH, 1).add(Aspect.ORDER, 1).add(Aspect.ENTROPY, 1), new ItemStack(ModItems.SCYTHE_THAUM), new Object[] { "AAA", "  B", "  B", Character.valueOf('A'), new ItemStack(ItemsTC.ingots, 1, 0), Character.valueOf('B'), Items.STICK }));
/*  99 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "scythe_void"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "scythe_void"), "TG_SCYTHES", 75, (new AspectList()).add(Aspect.AIR, 1).add(Aspect.FIRE, 1).add(Aspect.WATER, 1).add(Aspect.EARTH, 1).add(Aspect.ORDER, 1).add(Aspect.ENTROPY, 1), new ItemStack(ModItems.SCYTHE_VOID), new Object[] { "AAA", "  B", "  B", Character.valueOf('A'), new ItemStack(ItemsTC.ingots, 1, 1), Character.valueOf('B'), Items.STICK }));
/*     */     
/* 101 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "pouch_magic_1"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "pouch_magic_1"), "TG_BAGS", 50, new AspectList(), new ItemStack(ModItems.MAGIC_POUCH), new Object[] { " A ", "AAA", "AAA", Character.valueOf('A'), ItemsTC.fabric }));
/*     */     
/* 103 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "pouch_magic_2"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "pouch_magic_2"), "TG_BAGS", 75, new AspectList(), new ItemStack(ModItems.ENCHANTED_POUCH), new Object[] { " A ", "AAA", "AAA", Character.valueOf('A'), ModItems.FABRIC_ENCHANTED }));
/* 104 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_magic_2_1"), new InfusionRecipe("TG_BAGS", new ItemStack(ModItems.ENCHANTED_POUCH), 2, (new AspectList()).add(Aspect.EXCHANGE, 25).add(Aspect.MAGIC, 50).add(Aspect.TOOL, 20), new ItemStack(ModItems.MAGIC_POUCH), new Object[] { new ItemStack(ModItems.FABRIC_ENCHANTED), new ItemStack(ModItems.FABRIC_ENCHANTED), new ItemStack(ModItems.FABRIC_ENCHANTED), new ItemStack(ModItems.FABRIC_ENCHANTED) }));
/*     */     
/* 106 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "pouch_magic_3"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "pouch_magic_3"), "TG_BAGS", 100, new AspectList(), new ItemStack(ModItems.BEWITCHED_POUCH), new Object[] { " A ", "AAA", "AAA", Character.valueOf('A'), ModItems.FABRIC_BEWITCHED }));
/* 107 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_magic_3_1"), new InfusionRecipe("TG_BAGS", new ItemStack(ModItems.BEWITCHED_POUCH), 4, (new AspectList()).add(Aspect.EXCHANGE, 45).add(Aspect.MAGIC, 80).add(Aspect.TOOL, 40), new ItemStack(ModItems.ENCHANTED_POUCH), new Object[] { new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED) }));
/*     */     
/* 109 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_hungry_magic_1"), new InfusionRecipe("TG_HUNGRY_BAGS", new ItemStack(ModItems.HUNGRY_MAGIC_POUCH), 3, (new AspectList()).add(Aspect.VOID, 30).add(Aspect.AURA, 10).add(Aspect.MAGIC, 30).add(Aspect.TOOL, 20), new ItemStack(ModItems.MAGIC_POUCH), new Object[] { new ItemStack(Item.getItemFromBlock(BlocksTC.hungryChest)), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE) }));
/*     */     
/* 111 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_hungry_magic_2"), new InfusionRecipe("TG_HUNGRY_BAGS", new ItemStack(ModItems.HUNGRY_ENCHANTED_POUCH), 5, (new AspectList()).add(Aspect.VOID, 40).add(Aspect.AURA, 12).add(Aspect.MAGIC, 40).add(Aspect.TOOL, 25), new ItemStack(ModItems.ENCHANTED_POUCH), new Object[] { new ItemStack(Item.getItemFromBlock(BlocksTC.hungryChest)), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE) }));
/* 112 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_hungry_magic_2_1"), new InfusionRecipe("TG_HUNGRY_BAGS", new ItemStack(ModItems.HUNGRY_ENCHANTED_POUCH), 5, (new AspectList()).add(Aspect.VOID, 40).add(Aspect.AURA, 12).add(Aspect.MAGIC, 40).add(Aspect.TOOL, 25), new ItemStack(ModItems.HUNGRY_MAGIC_POUCH), new Object[] { new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED) }));
/*     */     
/* 114 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_hungry_magic_3"), new InfusionRecipe("TG_HUNGRY_BAGS", new ItemStack(ModItems.HUNGRY_BEWITCHED_POUCH), 7, (new AspectList()).add(Aspect.VOID, 50).add(Aspect.AURA, 15).add(Aspect.MAGIC, 50).add(Aspect.TOOL, 30), new ItemStack(ModItems.BEWITCHED_POUCH), new Object[] { new ItemStack(Item.getItemFromBlock(BlocksTC.hungryChest)), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE) }));
/* 115 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_hungry_magic_3_1"), new InfusionRecipe("TG_HUNGRY_BAGS", new ItemStack(ModItems.HUNGRY_BEWITCHED_POUCH), 7, (new AspectList()).add(Aspect.VOID, 50).add(Aspect.AURA, 15).add(Aspect.MAGIC, 50).add(Aspect.TOOL, 30), new ItemStack(ModItems.HUNGRY_ENCHANTED_POUCH), new Object[] { new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED) }));
/*     */     
/* 117 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_ender"), new InfusionRecipe("TG_ENDER_BAG", new ItemStack(ModItems.ENDER_POUCH), 5, (new AspectList()).add(Aspect.VOID, 20).add(Aspect.MAGIC, 50).add(Aspect.TOOL, 20).add(Aspect.MOTION, 75).add(Aspect.ELDRITCH, 35), new ItemStack(ModItems.MAGIC_POUCH), new Object[] { new ItemStack(Items.ENDER_PEARL), new ItemStack(Items.ENDER_PEARL), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED) }));
/*     */     
/* 119 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "pouch_void"), new InfusionRecipe("TG_VOID_BAG", new ItemStack(ModItems.VOID_POUCH), 6, (new AspectList()).add(Aspect.VOID, 100).add(Aspect.MAGIC, 50).add(Aspect.MOTION, 25), new ItemStack(ModItems.ENDER_POUCH), new Object[] { new ItemStack(ItemsTC.voidSeed), new ItemStack(ItemsTC.voidSeed), new ItemStack(ModItems.FABRIC_BEWITCHED), new ItemStack(ModItems.FABRIC_BEWITCHED) }));
/*     */     
/* 121 */     ThaumcraftApi.addArcaneCraftingRecipe(new ResourceLocation("tg", "ageing_stone"), (IArcaneRecipe)new ShapedArcaneRecipe(new ResourceLocation("tg", "ageing_stone"), "TG_AGEING_STONE", 0, (new AspectList()).add(Aspect.ORDER, 10).add(Aspect.ENTROPY, 10), new ItemStack(ModBlocks.AGEING_STONE), new Object[] { " A ", "BCB", " A ", Character.valueOf('A'), ItemsTC.salisMundus, Character.valueOf('B'), BlocksTC.stoneArcane, Character.valueOf('C'), Items.CLOCK }));
/*     */     
/* 123 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "helmet_light"), (new InfusionRecipe("TG_LIGHT_METAL", new ItemStack(ModItems.HELMET_LIGHT), 9, (new AspectList()).add(Aspect.METAL, 160).add(Aspect.PROTECT, 160).add(Aspect.MAGIC, 80).add(Aspect.AURA, 40).add(Aspect.EXCHANGE, 80).add(Aspect.LIGHT, 160).add(Aspect.ENERGY, 160), new ItemStack(ItemsTC.fortressHelm), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_armor")));
/* 124 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "helmet_shade"), (new InfusionRecipe("TG_SHADOW_METAL", new ItemStack(ModItems.HELMET_SHADE), 9, (new AspectList()).add(Aspect.METAL, 160).add(Aspect.PROTECT, 160).add(Aspect.MAGIC, 80).add(Aspect.AURA, 40).add(Aspect.EXCHANGE, 80).add(Aspect.DARKNESS, 160).add(Aspect.VOID, 160), new ItemStack(ItemsTC.fortressHelm), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_armor")));
/*     */     
/* 126 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "chestplate_light"), (new InfusionRecipe("TG_LIGHT_METAL", new ItemStack(ModItems.CHESTPLATE_LIGHT), 11, (new AspectList()).add(Aspect.METAL, 200).add(Aspect.PROTECT, 200).add(Aspect.MAGIC, 100).add(Aspect.AURA, 50).add(Aspect.EXCHANGE, 100).add(Aspect.LIGHT, 200).add(Aspect.ENERGY, 200), new ItemStack(ItemsTC.fortressChest), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_armor")));
/* 127 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "chestplate_shade"), (new InfusionRecipe("TG_SHADOW_METAL", new ItemStack(ModItems.CHESTPLATE_SHADE), 11, (new AspectList()).add(Aspect.METAL, 200).add(Aspect.PROTECT, 200).add(Aspect.MAGIC, 100).add(Aspect.AURA, 50).add(Aspect.EXCHANGE, 100).add(Aspect.DARKNESS, 200).add(Aspect.VOID, 200), new ItemStack(ItemsTC.fortressChest), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_armor")));
/*     */     
/* 129 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "leggins_light"), (new InfusionRecipe("TG_LIGHT_METAL", new ItemStack(ModItems.LEGGINS_LIGHT), 11, (new AspectList()).add(Aspect.METAL, 200).add(Aspect.PROTECT, 200).add(Aspect.MAGIC, 100).add(Aspect.AURA, 50).add(Aspect.EXCHANGE, 100).add(Aspect.LIGHT, 200).add(Aspect.ENERGY, 200), new ItemStack(ItemsTC.fortressLegs), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_armor")));
/* 130 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "leggins_shade"), (new InfusionRecipe("TG_SHADOW_METAL", new ItemStack(ModItems.LEGGINS_SHADE), 11, (new AspectList()).add(Aspect.METAL, 200).add(Aspect.PROTECT, 200).add(Aspect.MAGIC, 100).add(Aspect.AURA, 50).add(Aspect.EXCHANGE, 100).add(Aspect.DARKNESS, 200).add(Aspect.VOID, 200), new ItemStack(ItemsTC.fortressLegs), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_armor")));
/*     */     
/* 132 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "boots_light"), (new InfusionRecipe("TG_LIGHT_METAL", new ItemStack(ModItems.BOOTS_LIGHT), 9, (new AspectList()).add(Aspect.METAL, 160).add(Aspect.PROTECT, 160).add(Aspect.MAGIC, 80).add(Aspect.AURA, 40).add(Aspect.EXCHANGE, 80).add(Aspect.LIGHT, 160).add(Aspect.ENERGY, 160), new ItemStack(ItemsTC.travellerBoots), new Object[] { new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "light_armor")));
/* 133 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "boots_shade"), (new InfusionRecipe("TG_SHADOW_METAL", new ItemStack(ModItems.BOOTS_SHADE), 9, (new AspectList()).add(Aspect.METAL, 160).add(Aspect.PROTECT, 160).add(Aspect.MAGIC, 80).add(Aspect.AURA, 40).add(Aspect.EXCHANGE, 80).add(Aspect.DARKNESS, 160).add(Aspect.VOID, 160), new ItemStack(ItemsTC.travellerBoots), new Object[] { new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ItemsTC.ingots, 1, 0), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) })).setGroup(new ResourceLocation("tg", "shade_armor")));
/*     */     
/* 135 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "belt_light"), new InfusionRecipe("TG_BELT_LIGHT", new ItemStack(ModItems.BELT_LIGHT), 15, (new AspectList()).add(Aspect.METAL, 100).add(Aspect.PROTECT, 300).add(Aspect.MAGIC, 200).add(Aspect.AURA, 100).add(Aspect.LIGHT, 250).add(Aspect.ENERGY, 250), new ItemStack(ItemsTC.baubles, 1, 6), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.INGOT_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_LIGHT), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) }));
/* 136 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "belt_shade"), new InfusionRecipe("TG_BELT_SHADOW", new ItemStack(ModItems.BELT_SHADE), 15, (new AspectList()).add(Aspect.METAL, 100).add(Aspect.PROTECT, 300).add(Aspect.MAGIC, 200).add(Aspect.AURA, 100).add(Aspect.DARKNESS, 250).add(Aspect.VOID, 250), new ItemStack(ItemsTC.baubles, 1, 6), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.INGOT_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_SHADE), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.salisMundus) }));
/*     */     
/* 138 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "helmet_primal"), new InfusionRecipe("TG_PRIMAL_ARMOR", new ItemStack(ModItems.HELMET_PRIMAL), 12, (new AspectList()).add(Aspect.METAL, 300).add(Aspect.PROTECT, 300).add(Aspect.MAGIC, 150).add(Aspect.AURA, 60).add(Aspect.EXCHANGE, 60).add(Aspect.ORDER, 60).add(Aspect.ENTROPY, 60).add(Aspect.AIR, 60).add(Aspect.FIRE, 60).add(Aspect.WATER, 60).add(Aspect.EARTH, 60), new ItemStack(ItemsTC.fortressHelm), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(Item.getItemFromBlock(Blocks.GLASS)), new ItemStack(Item.getItemFromBlock(Blocks.GLASS)) }));
/* 139 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "chestplate_primal"), new InfusionRecipe("TG_PRIMAL_ARMOR", new ItemStack(ModItems.CHESTPLATE_PRIMAL), 15, (new AspectList()).add(Aspect.METAL, 400).add(Aspect.PROTECT, 400).add(Aspect.MAGIC, 200).add(Aspect.AURA, 80).add(Aspect.EXCHANGE, 80).add(Aspect.ORDER, 80).add(Aspect.ENTROPY, 80).add(Aspect.AIR, 80).add(Aspect.FIRE, 80).add(Aspect.WATER, 80).add(Aspect.EARTH, 80), new ItemStack(ItemsTC.fortressChest), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator) }));
/* 140 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "leggins_primal"), new InfusionRecipe("TG_PRIMAL_ARMOR", new ItemStack(ModItems.LEGGINS_PRIMAL), 15, (new AspectList()).add(Aspect.METAL, 400).add(Aspect.PROTECT, 400).add(Aspect.MAGIC, 200).add(Aspect.AURA, 80).add(Aspect.EXCHANGE, 80).add(Aspect.ORDER, 80).add(Aspect.ENTROPY, 80).add(Aspect.AIR, 80).add(Aspect.FIRE, 80).add(Aspect.WATER, 80).add(Aspect.EARTH, 80), new ItemStack(ItemsTC.fortressLegs), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator) }));
/* 141 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "boots_primal"), new InfusionRecipe("TG_PRIMAL_ARMOR", new ItemStack(ModItems.BOOTS_PRIMAL), 12, (new AspectList()).add(Aspect.METAL, 300).add(Aspect.PROTECT, 300).add(Aspect.MAGIC, 150).add(Aspect.AURA, 60).add(Aspect.EXCHANGE, 60).add(Aspect.ORDER, 60).add(Aspect.ENTROPY, 60).add(Aspect.AIR, 60).add(Aspect.FIRE, 60).add(Aspect.WATER, 60).add(Aspect.EARTH, 60), new ItemStack(ItemsTC.travellerBoots), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(Item.getItemFromBlock(ModBlocks.SHADE_BLOCK)), new ItemStack(Item.getItemFromBlock(ModBlocks.LIGHT_BLOCK)), new ItemStack(Item.getItemFromBlock(BlocksTC.metalBlockVoid)), new ItemStack(ItemsTC.salisMundus), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ModItems.FABRIC_VOLATILE), new ItemStack(ModItems.FABRIC_VOLATILE) }));
/*     */     
/* 143 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "helmet_primal_up"), new InfusionRecipe("TG_BETTER_PRIMAL_ARMOR", new ItemStack(ModItems.HELMET_PRIMAL_UP), 16, (new AspectList()).add(Aspect.ENERGY, 400).add(Aspect.PROTECT, 50).add(Aspect.MAGIC, 200).add(Aspect.AURA, 80).add(Aspect.EXCHANGE, 80).add(Aspect.ORDER, 160).add(Aspect.ENTROPY, 160).add(Aspect.AIR, 160).add(Aspect.FIRE, 160).add(Aspect.WATER, 160).add(Aspect.EARTH, 160), new ItemStack(ModItems.HELMET_PRIMAL), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.voidSeed) }));
/* 144 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "chestplate_primal_up"), new InfusionRecipe("TG_BETTER_PRIMAL_ARMOR", new ItemStack(ModItems.CHESTPLATE_PRIMAL_UP), 20, (new AspectList()).add(Aspect.ENERGY, 500).add(Aspect.PROTECT, 60).add(Aspect.MAGIC, 250).add(Aspect.AURA, 100).add(Aspect.EXCHANGE, 100).add(Aspect.ORDER, 200).add(Aspect.ENTROPY, 200).add(Aspect.AIR, 200).add(Aspect.FIRE, 200).add(Aspect.WATER, 200).add(Aspect.EARTH, 200), new ItemStack(ModItems.CHESTPLATE_PRIMAL), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.voidSeed) }));
/* 145 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "leggins_primal_up"), new InfusionRecipe("TG_BETTER_PRIMAL_ARMOR", new ItemStack(ModItems.LEGGINS_PRIMAL_UP), 20, (new AspectList()).add(Aspect.ENERGY, 500).add(Aspect.PROTECT, 60).add(Aspect.MAGIC, 250).add(Aspect.AURA, 100).add(Aspect.EXCHANGE, 100).add(Aspect.ORDER, 200).add(Aspect.ENTROPY, 200).add(Aspect.AIR, 200).add(Aspect.FIRE, 200).add(Aspect.WATER, 200).add(Aspect.EARTH, 200), new ItemStack(ModItems.LEGGINS_PRIMAL), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.voidSeed) }));
/* 146 */     ThaumcraftApi.addInfusionCraftingRecipe(new ResourceLocation("tg", "boots_primal_up"), new InfusionRecipe("TG_BETTER_PRIMAL_ARMOR", new ItemStack(ModItems.BOOTS_PRIMAL_UP), 16, (new AspectList()).add(Aspect.ENERGY, 400).add(Aspect.PROTECT, 50).add(Aspect.MAGIC, 200).add(Aspect.AURA, 80).add(Aspect.EXCHANGE, 80).add(Aspect.ORDER, 160).add(Aspect.ENTROPY, 160).add(Aspect.AIR, 160).add(Aspect.FIRE, 160).add(Aspect.WATER, 160).add(Aspect.EARTH, 160), new ItemStack(ModItems.BOOTS_PRIMAL), new Object[] { new ItemStack(ItemsTC.primordialPearl, 1, 32767), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.visResonator), new ItemStack(ItemsTC.voidSeed) }));

/* 160 */     }
/*     */ }


/* Location:              C:\Users\戴尔\Desktop\code\Thaumic_Gadgets_1.12.2_0.1.6_tb.26.jar!\com\ancient\thaumicgadgets\init\ModRecipes.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */